### ISSUE TITLE
Did u try to compile the client?

### ISSUE THREAD

**Issue by ekmekovski** [EiSiMo/Backdoor#8]
Hello sir,
Firstly thanx for ur beautiful repo, I really like it. But there is a problem, when I compile it , the client enter to a infinite loop. How can I solve this issue.

**Comment by tkgo11** [comment]
It helped me 
adding
```
import multiprocessing

if __name__ == '__main__':

    # Pyinstaller fix
    multiprocessing.freeze_support()
```
https://github.com/pyinstaller/pyinstaller/issues/1921#issuecomment-778455888
